#!/bin/tcsh
# run C test
#rm -rf cctest
#cp -r ccresult cctest
echo " Run C test:"
../bin/aftan_c_test paratest1.dat
# run gfortran test
#echo " Run gfortran test:"
#../bin/aftan_f_test paramf.dat
exit
