#!/bin/tcsh
set alpha=2500
set lamda=10
set sigma=50
../bin/tomo_sp_cu_s data25.0s.dat TEST_${lamda}_${sigma}_${alpha} 20 << EOF
me
0
1
4
5
23 29.5 0.4
6
98 107 0.4
8
30
9
3
10
.025
2
R
G
0.4
0.4
11
0
12
$alpha
$lamda
$sigma
$sigma
16
contour.ctr
17
init.mod
18
PREM.MODEL
19
23
0.0 0.0
25
26
x
v
go
EOF
exit
